### ISSUE TITLE
Get the id of the last inserted record

### ISSUE THREAD

**Issue by danbuntu** [knadh/localStorageDB#15]
Hello

Is there a quick way to get the ID of the last inserted record?
Or do I need to do an insert
then a get all
then get the highest ID?

**Comment by J06** [comment]
can you give the syntax using insert() function to get the id and store it in a variable?

**Comment by knadh** [comment]
`var id = lib.insert("books", {code: "B001", title: "Phantoms in the brain", author: "Ramachandran", year: 1999, copies: 10});
`
