### ISSUE TITLE
Better type checking for updates

### ISSUE THREAD

**Issue by albertogasparin** [knadh/localStorageDB#16]
This code updates all the records instead of none:

```
db.insertOrUpdate("table", { field: 0 }, { 'field': 5 });
```

The issue should be on `validFields()` function, where you are doing a "simple" `if(data[field])` instead of a type checking.

**Comment by w35l3y** [comment]
It was fixed in Nov 4th, 2013 and updated in Mar 13rd, 2014

https://github.com/w35l3y/localStorageDB/blame/ab7c0a227ecaecbe6c92db98e4ce831994cd6dfc/localstoragedb.js#L346
https://github.com/w35l3y/localStorageDB/blame/master/localstoragedb.js#L387

This issue may be closed.
