### ISSUE TITLE
insertOrUpdate - Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by danbuntu** [knadh/localStorageDB#53]
I'm trying to use  insertOrUpdate  and I'm getting the error:

Cannot read property 'toString' of null

I'm using the following code;

lib.insertOrUpdate("settings", {name: 'sound'}, {
                name: "sound",
                gameState: "0",
                desc: "Turns sound on and off"
            });

What am I doing wrong please?

**Comment by knadh** [comment]
The snippet looks fine. Can you share the rest of the code? (DB
initialisation and population)

**Comment by danbuntu** [comment]
the full code for the block looks lile:


var lib = new localStorageDB("carc", localStorage),
        existsSettings = lib.tableExists("settings"),

 if (existsSettings === false) {
        lib.createTable("settings", ["name", "gameState", "desc"]);
        lib.insert("settings", {name: "gamestate", gameState: "maingame", desc: "sets the current game state"});
        lib.insert("settings", {name: "slidertype", gameState: "0", desc: "sets slider type 0 = slider 1 = buttons"});
        lib.insert("settings", {name: "sound", gameState: "0", desc: "Turns sound on and off"});
        lib.commit();
    } else {
        // check for sound in the setting table and add if needed
            lib.insertOrUpdate("settings", {name: 'sound'}, {
                name: "sound",
                gameState: "0",
                desc: "turns sound on and off"
           });
       lib.commit();

        }

**Comment by knadh** [comment]
existsSettings = lib.tableExists("settings"),

^ this statement has to terminate with a semi column, yes?

**Comment by danbuntu** [comment]
sorry yes bad cut and paste on my part

**Comment by knadh** [comment]
The problem must be elsewhere. I tested the following and it worked fine.

```javascript
var lib = new localStorageDB("carc", localStorage),
    existsSettings = lib.tableExists("settings");

if (existsSettings === false) {
    lib.createTable("settings", ["name", "gameState", "desc"]);
    lib.insert("settings", {name: "gamestate", gameState: "maingame", desc: "sets the current game state"});
    lib.insert("settings", {name: "slidertype", gameState: "0", desc: "sets slider type 0 = slider 1 = buttons"});
    lib.insert("settings", {name: "sound", gameState: "0", desc: "Turns sound on and off"});
    lib.commit();
} else {
    // check for sound in the setting table and add if needed
    lib.insertOrUpdate("settings", {name: 'sound'}, {
        name: "sound",
        gameState: "0",
        desc: "turns sound on and off"
    });
    lib.commit();
}
console.log(lib.queryAll("settings"));
```

**Comment by danbuntu** [comment]
hmm blast. I'll keep digging - thanks for your time
