### ISSUE TITLE
I created a Typescript .d.ts definition file for localStorageDB.

### ISSUE THREAD

**Issue by a904guy** [knadh/localStorageDB#54]
[localStorageDB.d.ts](https://github.com/a904guy/Typescript-Typings/blob/master/typings/localStorageDB.d.ts)

Will allow people to use this library with Typescript.

**Comment by a904guy** [comment]
@knadh would you mind if I committed it with pull request?

**Comment by knadh** [comment]
That's nice! Send a pull request please.

**Comment by a904guy** [comment]
knadh/localStorageDB#55

**Comment by knadh** [comment]
Done.
