### ISSUE TITLE
Setting the column names in queryAll ()

### ISSUE THREAD

**Issue by danieldacruzferreira** [knadh/localStorageDB#56]
Is there a way to define the name of the columns that are returned in queryAll ()?

LIke this: db.queryAll("table_name", {'columns': ['Colum A', 'Colum B', 'Colum C']});

**Comment by knadh** [comment]
@danieldacruzferreira It is not possible to specify which columns are returned.

**Comment by danieldacruzferreira** [comment]
Ok,
Thank You @knadh
