### ISSUE TITLE
does this work with mobile browsers?

### ISSUE THREAD

**Issue by felix822** [knadh/localStorageDB#57]
Chrome for iOS, Safari iOS, etc.

**Comment by knadh** [comment]
Yes. It should work on all browsers that support HTML localStorage.

**Comment by linslin** [comment]
In fact, it does not support every mobile browser. 

#### Opera Mini is not supported:
http://caniuse.com/#search=localstorage

**Comment by knadh** [comment]
@linslin yes, only on browsers that support localStorage, as the library itself is an abstraction over localStorage.

**Comment by linslin** [comment]
@knadh -> cheers! :)

Added this informations into readme.md here https://github.com/knadh/localStorageDB/pull/58
