### ISSUE TITLE
Testing db integrity

### ISSUE THREAD

**Issue by danbuntu** [knadh/localStorageDB#62]
As some point I've made a mistake in my app and the db has become corrupt and I get a warning in the the console. 

'unexpected string'

You can simulate this by just manually removing one of the characters.

Is there a best way to test and possibly fix the integrity of the database?

**Comment by knadh** [comment]
@danbuntu the library should not corrupt the serialised data stored (JSON) in the database as it doesn't do any string manipulation, and it doesn't expose any methods to do so either. If the stored data is indeed somehow corrupted, there is no way to correct it without manually fixing it. Thanks.
