### ISSUE TITLE
Firefox storing localstorage database as string

### ISSUE THREAD

**Issue by schoettler** [knadh/localStorageDB#63]
Hey guys!

Just recently checked through *Firebug* how the library works on Firefox, and the object is being stored as a string (surrounded by double quotes), instead of an object e.g.: "{}" instead of {}, rendering the library unusable.

Is there anything we can do?

**Comment by knadh** [comment]
localStorage can only store strings. The library is built to work with
this. What do you mean by "unusable"? Have you tried the library at all?

**Comment by schoettler** [comment]
True, the problem had nothing to do with the library, sorry about that.
