### ISSUE TITLE
deleteRows() method: Deleting rows of the results that were queried before.

### ISSUE THREAD

**Issue by jeffreyyong** [knadh/localStorageDB#65]
I have queried the result in this step: 
"
var negativeQueryResult = localDatabase.queryAll("localPuzzleDatabase", {
                query: function (row) {
                    if (row.type == "negative") {
                        return true;
                    } else {
                        return false;
                    }
                },
                limit: 1
            });
"

And I would like to delete the row of queried result from the localStorage database. I am wondering what is the best approach of doing that?

I am currently using this step but it does not seem to work:

"
localDatabase.deleteRows("localPuzzleDatabase", {negativeQueryResult});
            localDatabase.commit();
"

**Comment by knadh** [comment]
Your code has a syntax error. This should work.

`localDatabase.deleteRows("localPuzzleDatabase", negativeQueryResult);`
