### ISSUE TITLE
GroupBy SQL Query

### ISSUE THREAD

**Issue by wangxianzhe015** [knadh/localStorageDB#69]
This plugin is nice to use. But I want to know how to implement `group by` statement in SQL query.

**Comment by knadh** [comment]
I am afraid the lib doesn't provide any form of SQL support.

**Comment by wangxianzhe015** [comment]
Is there no way to implement `group by` statement?
Or may I try to implement the functionality?
I hope someone help me with this issue :)

**Comment by knadh** [comment]
It is technically possible for sure. You can have a go at it.
