### ISSUE TITLE
queryAll query returns Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by brunodeprez** [knadh/localStorageDB#71]
Hi,

if the local database contains a null value for a property used by the queryAll query, it generates an exception.

```
var lib = new localStorageDB("carc", localStorage);
            if(!lib.tableExists("settings")) {
              lib.createTable("settings", ["name", "gameState", "desc"]);
              lib.insert("settings", {name: null,gameState: "maingame", desc: "sets the current game state"});
              lib.insert("settings", {name: "slidertype",gameState: "0",desc: "sets slider type 0 = slider 1 = buttons"});
              lib.insert("settings", {name: "sound", gameState: "0", desc: "Turns sound on and off"});
              lib.commit();
            }
            var searchObject = {name:"slidertype"}
            console.log(lib.queryAll("settings",{query:searchObject}));
```

-> Cannot read property 'toString' of null

null values should simply be filtered out of the returned array

Can be fixed by simply adding row 253:

```
if(!row[field]){
            exists = false;
            break;
          }
```

I can also do a pull request if needed

Thanks

**Comment by w35l3y** [comment]
What version are you importing ? Normal or minified version ?

Normal version was fixed 2 years ago.
https://github.com/knadh/localStorageDB/blame/master/localstoragedb.js#L254

**Comment by w35l3y** [comment]
A good PR would be to make `localstoragedb.min.js` be created automatically.

**Comment by knadh** [comment]
Just updated the minified version. I haven't been maintaining this repo properly ;(
