### ISSUE TITLE
Not supporting cross-tabs

### ISSUE THREAD

**Issue by drveresh** [knadh/localStorageDB#72]
Hi,

Currently it is only supporting same page/tab, but not working in multiple tabs for same pages/application.  Now days, it is a basic use case that users would open same app on multiple tabs.

Please update me if this can be accommodated.

- Thanks

**Comment by knadh** [comment]
That's not how localStorage works. It uses the domain name, not browser sessions or tabs for storage. Similar to how cookies work. You may be initialising and wiping your localSotrageDB instance on every page load. Please share your code snippets here if possible.

**Comment by drveresh** [comment]
I agree that by default the localStorage doesn't support syncing between more than one tab for same website/page/domain, and I was hoping your library will cover it.

**Comment by knadh** [comment]
On the contrary, as I said, localStorage is tied to domain names. Once a value is set, it should become available across multiple tabs (of the same domain) instantly.
