### ISSUE TITLE
Migrate database when update schema?

### ISSUE THREAD

**Issue by TranDinhKhang** [knadh/localStorageDB#75]
I already had a table by run the code `db.createTable('auth', ['username', 'password'])` in the first deployment. The table 'auth' already have data.
And I want to add 2 more columns like 'full_name' and 'avatar_link' into that table without dropping and creating it.
How can I do that?

**Comment by w35l3y** [comment]
There is a function called `db.alterTable(tableName, arrayNewFields, objectDefaultValues)`.

Based on your example, it would be: 
```
db.alterTable('auth', ['full_name', 'avatar_link'], {'full_name':null, 'avatar_link':null})
```
This issue may be closed.
